name: Run tests

on:
  push:
    branches: [
      "main"
    ]
  pull_request:
    branches: [
      "main"
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  php-run-tests:
    uses: ./.github/workflows/_php-run-tests.yml
